### ISSUE TITLE
Need some help to hide some modules

### ISSUE THREAD

**Issue by bert269** [Trekky12/MMM-ModuleToggle#1]
Hi,
I know this is not an issue, but I followed your instructions and cannot seem to be able to hide certain modules.
So I have MMM-ModuleToggle defined as:
{ module: 'MMM-ModuleToggle',
	config: { hide: [], show:[], toggle:[]} 
}

And I have four modules: A, B, C and D. A,B,C gets started with MagicMirror. D is a ScreenCast module that gets triggered from my cell phone. So the 'invoking module D' is coded as:
{ module 'D',
notification: "MODULE_TOGGLE", payload: {hide: ["A","B","C"], show:[], toggle:[]},....

But it does not hide the other modules (A,B and C) when D is activated.

Can you please tell me what I am missing here?
Thanks

**Comment by Trekky12** [comment]
Hey @bert269,

the invoking module needs to implement the possibility to send notifications to other modules.
You can see the documentation for this feature at https://docs.magicmirror.builders/development/core-module-file.html#module-instance-methods

A example module is the MMM-Buttons module. The code is here https://github.com/Jopyth/MMM-Buttons/blob/master/MMM-Buttons.js#L88

If the module doesn't support sending notifications this is not possible. 

Could you name or show the screencast module? What is your desired trigger? When a video is streamed?

**Comment by bert269** [comment]
@Trekky12 

Thank you so much for the info and your help. I do appreciate this. Going through this button code, makes my head spin!

This is the module that must disable/hide the following mentioned module upon invocation and enable /show again upon exit : https://github.com/kevinatown/MMM-Screencast

The module that must be turned on and off:
https://github.com/AdamMoses-GitHub/MMM-ImageSlideshow

Thank you so much?

**Comment by Trekky12** [comment]
Thank you for your description. I've added a new feature to trigger module changes by notifications emitted by other modules.

You need to define these triggers in the config like that:
```
{
    module: 'MMM-ModuleToggle',
    config: {
        hide: ["clock"],                                 // hide on start
        notifications: [
                {
                    notification: "MMM-Screencast:RUN-APP",
                    hide: ["MMM-ImageSlideshow"],        // list of modules to hide
                    show: [],                            // list of modules to show
                    toggle: [],                          // list of modules to toggle
                },
                {
                    notification: "MMM-Screencast:STOP-APP",
                    show: ["MMM-ImageSlideshow"]
                }
        ]
    }
}
```

The emitted notifications of the MMM-Screencast module are described here: https://github.com/kevinatown/MMM-Screencast#emmited-notifications
