### ISSUE TITLE
Ability to hide a certain instance of a module

### ISSUE THREAD

**Issue by Entropy159** [Trekky12/MMM-ModuleToggle#3]
I have a setup with the Game of Life module, and some Touch Button modules to control it. I also have another instance of the Touch Button module to toggle the Game of Life and its three Touch Buttons, but I get an error saying "Uncaught (in promise) TypeError: searchClasses is not iterable". My setup has the "toggle" set to {"MMM-GameOfLife", "module_11_MMM-TouchButton", "module_12_MMM-TouchButton", "module_13_MMM-TouchButton"}. Is there any workaround, or if not could you add this functionality?

**Comment by Trekky12** [comment]
Would that be fixed with your PR #4?

**Comment by Entropy159** [comment]
Yes. I found the issue was that the module searched for all the modules with those classes, and a specific instance ID is not a class so it would throw an error. I changed it so that it iterates through all the modules and checks if the config list matches either the module name "MMM-TouchButton" or the identifier "module_14_MMM-TouchButton".

**Comment by Entropy159** [comment]
P.S. the name and identifier I gave a just examples, it's not actually hardcoded with those.
